#!/bin/bash
# Generate image/proprietary-files.txt: the inventory of Google-proprietary files in our image.
set -uo pipefail

DEVICE="${DEVICE:-stallion}"
TREE="${GRAPHENE_TREE:-$PWD}"

note() { printf '# NOTE  %s\n' "$1"; }
die()  { printf 'list_google_files: %s\n' "$1" >&2; exit 2; }

[ -d "$TREE" ] || die "GRAPHENE_TREE=$TREE does not exist"

if command -v sha256sum >/dev/null 2>&1; then
  sha256() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1; then
  sha256() { shasum -a 256 "$@"; }
else
  die "neither sha256sum nor shasum is on PATH. Every entry in this inventory is a path AND a
       hash, so without one of them the only thing this script could emit is a list stamped
       COMPLETE with no evidence in it. Refusing."
fi

VENDOR_TREE=""
for cand in \
  "$TREE/vendor/google_devices/$DEVICE/proprietary" \
  "$TREE/vendor/google_devices/$DEVICE" \
  "$TREE/vendor/adevtool/dl/$DEVICE"; do
  if [ -d "$cand" ]; then VENDOR_TREE="$cand"; break; fi
done
[ -n "$VENDOR_TREE" ] || die "no extracted vendor tree under $TREE/vendor -- run './vendor/adevtool/bin/run generate-all -d $DEVICE' first"

STOCK_MK=""
for cand in "$TREE/vendor/google_devices/$DEVICE/$DEVICE.mk" \
            "$TREE/vendor/google_devices/$DEVICE.mk"; do
  [ -f "$cand" ] && { STOCK_MK="$cand"; break; }
done
[ -n "$STOCK_MK" ] || die "no generated $DEVICE.mk under $TREE/vendor/google_devices -- cannot
       determine which stock build these blobs were extracted from, and a guessed
       REQUIRED_STOCK_BUILD_ID would let punch_blobs.sh zero the wrong bytes"

STOCK_BUILD_ID="$(sed -n 's/^ifneq (\$(BUILD_ID),\([A-Za-z0-9._][A-Za-z0-9._]*\))[[:space:]]*$/\1/p' \
                  "$STOCK_MK" | head -1)"
[ -n "$STOCK_BUILD_ID" ] || die "$STOCK_MK has no 'ifneq (\$(BUILD_ID),...)' guard, so the stock
       build id cannot be read from it. Refusing to write a manifest with no build pin: see
       punch_blobs.sh:251 for what depends on it"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "# Google-proprietary files in a RistOS image for $DEVICE."
echo "#"
echo "# GENERATED by image/scripts/list_google_files.sh on $(date -u +%Y-%m-%d). Do not edit by"
echo "# hand: regenerate whenever the GrapheneOS base or the stock build id changes, or it will"
echo "# pass artefacts containing files it has never heard of."
echo "#"
echo "# DEVICE: $DEVICE"
echo "# REQUIRED_STOCK_BUILD_ID: $STOCK_BUILD_ID"
echo "#"
echo "# COMPLETE: yes"
echo "#"
echo "# Source tree: ${VENDOR_TREE#"$TREE"/}"
echo "#"
echo "# Format: <install path relative to the partition root>|<sha256 of the extracted bytes>"

# Keep NOT_INSTALLED in step with _rist_degoogle_modules in aosp/rist.mk.
NOT_INSTALLED="
product/priv-app/PixelCameraServices/PixelCameraServices.apk
system_ext/framework/com.google.android.camerax.extensions.jar
"

# NL makes this a whole-line match, not a substring one.
NL='
'
not_installed() {
  case "$NOT_INSTALLED" in
    *"$NL$1$NL"*) return 0 ;;
  esac
  return 1
}

count=0
skipped=0
while IFS= read -r -d '' f; do
  rel="${f#"$VENDOR_TREE"/}"
  if not_installed "$rel"; then
    printf '# NOT INSTALLED %s   (extracted by adevtool, overridden out of the image by aosp/rist.mk)\n' "$rel"
    skipped=$((skipped + 1))
    continue
  fi
  sum="$(sha256 "$f" | cut -d' ' -f1)"
  [ -n "$sum" ] || die "could not hash $f -- refusing to emit an inventory with a blank entry"
  printf '%s|%s\n' "$rel" "$sum"
  printf '%s\n' "$rel" >>"$TMP/seen"
  count=$((count + 1))
done < <(find "$VENDOR_TREE" -type f \
           ! -name 'Android.bp' ! -name 'Android.mk' ! -name '*.mk' \
           ! -name 'BoardConfig*' -print0 | sort -z)

note "pass 1: $count files from the extracted vendor tree"
n_not_installed="$(printf '%s\n' "$NOT_INSTALLED" | grep -c '[^[:space:]]')"
if [ "$skipped" -ne "$n_not_installed" ]; then
  note "pass 1: WARNING -- $n_not_installed paths are listed NOT_INSTALLED, but only $skipped of"
  note "pass 1: WARNING    them exist in the extracted tree. Check the list against \$VENDOR_TREE and"
  note "pass 1: WARNING    against _rist_degoogle_modules in aosp/rist.mk before trusting this file."
else
  note "pass 1: $skipped extracted files excluded as NOT INSTALLED (see the list in this script)"
fi

# Pass 2 emits CANDIDATE comments only: byte-identity also matches AOSP files GrapheneOS rebuilt.
PRODUCT_OUT_DIR="$TREE/out/target/product/$DEVICE"
touch "$TMP/seen"
if [ -z "${STOCK_UNPACKED:-}" ]; then
  note "pass 2 SKIPPED: set STOCK_UNPACKED=<dir of unpacked stock partitions> to cross-check"
  note "pass 2 SKIPPED means this list is adevtool's view only, not an independent audit"
elif [ ! -d "$PRODUCT_OUT_DIR" ]; then
  note "pass 2 SKIPPED: no staged image at $PRODUCT_OUT_DIR (run 'm' first)"
else
  extra=0
  while IFS= read -r -d '' f; do
    rel="${f#"$PRODUCT_OUT_DIR"/}"
    [ -f "$STOCK_UNPACKED/$rel" ] || continue
    grep -qxF "$rel" "$TMP/seen" && continue
    if cmp -s "$f" "$STOCK_UNPACKED/$rel"; then
      printf '# CANDIDATE %s|%s\n' "$rel" "$(sha256 "$f" | cut -d' ' -f1)"
      extra=$((extra + 1))
    fi
  done < <(find "$PRODUCT_OUT_DIR/system" "$PRODUCT_OUT_DIR/product" \
                "$PRODUCT_OUT_DIR/system_ext" "$PRODUCT_OUT_DIR/vendor" \
                -type f -print0 2>/dev/null | sort -z)
  note "pass 2: $extra files byte-identical to stock but absent from the extracted tree,"
  note "pass 2: emitted as '# CANDIDATE' comments, NOT as inventory entries. Expect this count to"
  note "pass 2: be in the thousands and to be mostly AOSP: on one stallion build it was"
  note "pass 2: ~1,126 open-source files against ~718 genuinely proprietary ones. Read before promoting."
fi

# v1 (JAR) signatures only; v2/v3-only APKs are not seen here.
GOOGLE_CERT_CN='O=Google Inc.'
if [ ! -d "$PRODUCT_OUT_DIR" ]; then
  note "pass 3 SKIPPED: no staged image at $PRODUCT_OUT_DIR (run 'm' first)"
elif ! command -v unzip >/dev/null 2>&1 || ! command -v openssl >/dev/null 2>&1; then
  note "pass 3 SKIPPED: needs unzip and openssl on PATH. NOT a clean result -- this is the only"
  note "pass 3 SKIPPED: definitive origin test in this script, and it did not run."
else
  gsigned=0
  while IFS= read -r -d '' f; do
    rel="${f#"$PRODUCT_OUT_DIR"/}"
    sig="$(unzip -Z1 "$f" 2>/dev/null | grep -iE '^META-INF/.*\.(RSA|DSA|EC)$' | head -1)"
    [ -n "$sig" ] || continue
    subj="$(unzip -p "$f" "$sig" 2>/dev/null \
            | openssl pkcs7 -inform DER -print_certs -noout 2>/dev/null \
            | sed -n 's/^subject=//p' | head -1)"
    case "$subj" in
      *"$GOOGLE_CERT_CN"*)
        grep -qxF "$rel" "$TMP/seen" && continue
        printf '%s|%s\n' "$rel" "$(sha256 "$f" | cut -d' ' -f1)"
        printf '%s\n' "$rel" >>"$TMP/seen"
        gsigned=$((gsigned + 1))
        ;;
    esac
  done < <(find "$PRODUCT_OUT_DIR/system" "$PRODUCT_OUT_DIR/product" \
                "$PRODUCT_OUT_DIR/system_ext" "$PRODUCT_OUT_DIR/vendor" \
                -type f -name '*.apk' -print0 2>/dev/null | sort -z)
  note "pass 3: $gsigned APKs signed with Google's certificate ($GOOGLE_CERT_CN), beyond pass 1"
  if [ "$gsigned" -eq 0 ]; then
    note "pass 3: zero BEYOND pass 1 is the expected result -- adevtool should already have them."
    note "pass 3: zero because nothing was scanned would look identical, so check the count above."
  fi
fi
